### ISSUE TITLE
Range scans on PK doesn't take advantage of PK order

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#105]
Queries like
`SELECT * FROM mytable WHERE pkfield >= v ORDER BY pkfield LIMIT n`
ideally should scan just n values.

Currently every value after v is retrieved, filtered and sorted before limiting the output.

Knownledge of ordering by pk should be push down in some way to data scanner with result limit knowledge too.

There should be some way to improve inverted pk order scanning too (ex: pk defined as ASC and ordering by DESC)

**Comment by eolivelli** [comment]
Pay attention to transactions
