### ISSUE TITLE
CLI: add admin-friendly tablespace management commands

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#112]
It would be great to have simple command on herddb-cli.sh to manage tablespaces and nodes.
Now you have to query directly systables, but it is quite difficult for "humans"

My proposal is to add commands like
`herddb-cli.sh --list-tablespaces`
This lists all available tablespaces for each tablespace at least we have to write the 'leader'

`herddb-cli.sh --show-tablespace -s TABLESPACENAME`

Show full info about a tablespace:
- configuration (select * from TABLESPACE.systablespaces where tablespace_name=?)
- replica state (select * from TABLESPACE.sysreplicastate where tablespace_name=?)
- number of tables ? (select count(*) from TABLESPACE.systables where tablespace_name=?)

```
herddb-cli.sh --add-replica -s TABLESPACENAME -r NODEID
herddb-cli.sh --remove-replica -s TABLESPACENAME -r NODEID
herddb-cli.sh --alter-tablespace -s TABLESPACENAME --param PARAM --value VALUE
```
for instance
```
herddb-cli.sh --alter-tablespace -s TABLESPACENAME --param leader --value NODEID
herddb-cli.sh --alter-tablespace -s TABLESPACENAME --param expectednumreplica --value 5
```

```
herddb-cli.sh --list-tables -s TABLESPACENAME

herddb-cli.sh --show-table -s TABLESPACENAME -t TABLENAME
```
(show table columns and indexes, using JDBC metadata ??)

**Comment by caiok** [comment]
In addition to above specifications, I added:

- A --list-nodes command
- A resultset formatter similar to mysql / psql ones

**Comment by caiok** [comment]
Added the --create-tablespace command
