### ISSUE TITLE
Support ALTER TABLE x MODIFY COLUMN syntax

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#117]
ALTER TABLE x MODIFY COLUMN should be supported.
Without support datatype changes must be done creating a new table (that cannot be renamed too). Even AUTO_INCREMENT flag cannot be added/removed too

**Comment by eolivelli** [comment]
pushed basic support for adding/removig auto_increment and for renaming columns (even PK columns)

indexes not covered
