### ISSUE TITLE
Support not-null constraints

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#125]
- support 'NOT NULL' at DDL level during "CREATE TABLE' and 'ADD COLUMN'
- enforce "NOT NULL' during DML operations
- inform Calcite that the column is NOT NULL (the Planner will keep it in consideration)

In the first implementation it is not needed to support 'NOT NULL' in ALTER TABLE DDL, because it would imply to check that the column is 'NOT NULL' for each record and this should be done in transaction with the DDL operation.

**Comment by eolivelli** [comment]
1) Support basic NOT NULL constrains
2) Support for JDBC metadata

beside note:
implicitly PK columns are "not null" so it must be reported by metadata

**Comment by eolivelli** [comment]
@amitvc this could be a good starting point.

**Comment by amitvc** [comment]
I will start work on this starting today.

**Comment by eolivelli** [comment]
@amitvc 
this is where we handle columns in CREATE TABLE
https://github.com/diennea/herddb/blob/8c371db08414603b5335f500cc75a792adb42156/herddb-core/src/main/java/herddb/sql/DDLSQLPlanner.java#L351

for DDL we are using jsqlparser and not Calcite (it is not directly actually supporteb by Calcite)

You can start checking tests in
https://github.com/diennea/herddb/blob/master/herddb-core/src/test/java/herddb/core/CreateTableTest.java
https://github.com/diennea/herddb/blob/master/herddb-core/src/test/java/herddb/core/AlterTablespaceSQLTest.java
https://github.com/diennea/herddb/blob/master/herddb-core/src/test/java/herddb/core/AlterTableSQLTest.java

The first step is to differenziate NULLABLE data types from NOT_NULLABLE data types here:
https://github.com/diennea/herddb/blob/master/herddb-core/src/main/java/herddb/model/ColumnTypes.java

for instance current 'STRING' data type will become NULLABLE_STRING, and you will introduce NOT_NULLABLE_STRING

**Comment by eolivelli** [comment]
I will write more ideas this evening

**Comment by amitvc** [comment]
@eolivelli thanks for the input.

**Comment by eolivelli** [comment]
@amitvc sorry for late reply.
The idea behind creating new column types is that if we add a new 'boolean' field to 'column' we will have to pass it down in all code paths and this will make us use more CPU cycles (passing parameters....) and error prone

**Comment by aluccaroni** [comment]
@eolivelli @amitvc  this can be closed?

**Comment by amitvc** [comment]
I think so. This is merged into master.
