### ISSUE TITLE
Check if epool is really available

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#158]
Fix epoll availability check invoking Epoll.isAvailable()

**Comment by diegosalvi** [comment]
Fixed on  both 0.1 and 0.2 branches

**Comment by eolivelli** [comment]
@diegosalvi great ! thank you

**Comment by eolivelli** [comment]
@diegosalvi  did you check on BK ? maybe we should add that test as well.
They are rolling 4.6 release candidate now, we can add an hotfix before the release
