### ISSUE TITLE
sql console: TRUNCATE command case sensitivity

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#159]
herd: truncate table usertable
Executing query:truncate table usetable
ERROR:java.sql.SQLException: herddb.model.StatementExecutionException: Encountered "truncate table" at line 1, column 1.

herd: TRUNCATE table usertable
Executing query:TRUNCATE table usertable
UPDATE COUNT: 0

The cli commands should be evaluated as case insensitive, same as before the 0.2 branch

**Comment by eolivelli** [comment]
closed with 9da1f9a
