### ISSUE TITLE
JDBC create table with a text field failed

### ISSUE THREAD

**Issue by victorlbb** [diennea/herddb#167]
The error is as below. But we can successfully create table in the using the interactive shell.
![wechatimg4070](https://user-images.githubusercontent.com/14255917/33971293-bab03ff0-e045-11e7-9559-bd40b899d120.jpeg)

**Comment by diegosalvi** [comment]
To me it seems a hdqldb error. Am I missing something?

**Comment by eolivelli** [comment]
@victorlbb did you see @diegosalvi comment ?

**Comment by eolivelli** [comment]
Closing this issue as it seems not related to HerdDB
