### ISSUE TITLE
HerdDB Logo?

### ISSUE THREAD

**Issue by apavlo** [diennea/herddb#193]
Is there a logo for this project? I would like to include it in my encyclopedia of databases:

https://dbdb.io/db/herddb

**Comment by eolivelli** [comment]
@apavlo

You can pick it from here, the last one
https://github.com/apache/calcite/pull/657

I can send you an email of the logo.
We have recently created the one for third parties, like the one in Apache Calcite

**Comment by eolivelli** [comment]
This one I mean 
https://user-images.githubusercontent.com/9469110/38733120-0d03640a-3f21-11e8-8295-5ab353430e3d.png

**Comment by eolivelli** [comment]
@pavlo thank you

**Comment by apavlo** [comment]
@eolivelli Done! Thanks

https://dbdb.io/db/herddb

**Comment by eolivelli** [comment]
@apavlo thank you too

Looks great!

Cheers
