### ISSUE TITLE
Support "select ... from FOR UPDATE" syntax

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#228]
Requested by @victorlbb in #166

**Comment by aluccaroni** [comment]
Requested by @rmannibucau in https://github.com/diennea/herddb/issues/631

"This prevents to use several JPA mapper without workarounds"

A possible workaround would be to use AUTO_INCREMENT, but this is not always feasible

**Comment by rmannibucau** [comment]
@aluccaroni not really cause only table generator is portable, auto increment generally does not enable to change of database.

**Comment by eolivelli** [comment]
released with 0.17.0
