### ISSUE TITLE
Strange join behaviour

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#262]
When I run this query no record with lic id 11 is found (but it should)

SELECT * FROM license t0, customer c WHERE c.customer_id = t0.customer_id

When I run this query magically the record appears

SELECT * FROM license t0, customer c WHERE c.customer_id = 3 AND t0.customer_id = 3 AND c.customer_id = t0.customer_id

Server backup attached

**Comment by diegosalvi** [comment]
[backupherd.zip](https://github.com/diennea/herddb/files/2405524/backupherd.zip)

**Comment by diegosalvi** [comment]
[dbdata.tar.gz](https://github.com/diennea/herddb/files/2405536/dbdata.tar.gz)

**Comment by eolivelli** [comment]
It seems that Calcite is planning a Merge Join, but the tables are not sorted according to the merge keys.

License table:
TABLE PK: [license_id]
COL: license_id serialPos: 0
COL: application serialPos: 1
COL: creation serialPos: 2
COL: data serialPos: 3
COL: deleted serialPos: 4
COL: modification serialPos: 5
COL: signature serialPos: 6
COL: customer_id serialPos: 7

customer table:
TABLE PK: [customer_id]
COL: customer_id serialPos: 0
COL: contact_email serialPos: 1
COL: contact_person serialPos: 2
COL: creation serialPos: 3
COL: deleted serialPos: 4
COL: modification serialPos: 5
COL: name serialPos: 6
COL: vetting serialPos: 7

the join is on PK (clustered) column of table customer,
and the "customer_id" column of table 'license' which is not sorted naturally by 'customerid', but by 'licenseid'




EnumerableMergeJoin(condition=[=($7, $9)], joinType=[inner]): rowcount = 15.75, cumulative cost = {59.75 rows, 24.0 cpu, 0.0 io}, id = 114
  EnumerableTableScan(table=[[herd, license]]): rowcount = 15.0, cumulative cost = {15.0 rows, 16.0 cpu, 0.0 io}, id = 28
  EnumerableTableScan(table=[[herd, customer]]): rowcount = 7.0, cumulative cost = {7.0 rows, 8.0 cpu, 0.0 io}, id = 29

**Comment by eolivelli** [comment]
To me it is not obvious that an EnumerableTableScan is sorted by the PK of the table (in HerdDB it is the case when using BLink, but not using transactions).

It is wrong to assume a sort by another Key.

I hope that it is not Calcite the bad guy but there is some bug in translation of EnumerableMergeJoin
