### ISSUE TITLE
Enhanced prepare statement support

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#290]
The idea is to introduce an official "support" for Prepared Statements, 
in the first form this is a way for a client to inform the server that it is going to issue the same SQL statement multiple times, this way:
- on the wire the client will send only a "statement id" (64bit signed long)
- the server can prepare/cache resources (this is actually not needed as we already have a server wide plans cache, but in the future we could have a smarter caching)
- the client may receive additional informations about the SQL, like the expected resultset schema, information about JDBC parameters....

In a first implementation we can have:
- a specific RPC PREPARE_SQL (the client sends a query and it receives the id)
- a client side (RoutedClientSideConnection) mapping  between the SQL text and the statement id
- a server side cache which maps the raw sql text with the id

the challenge is to automatically clean up the cache on the server side, because the server has no strong "notion" of "client" or JDBC Connection, we only have a ServerSideConnectionPeer which is bound to a specific "socket", but one client will use several sockets.

The first implementation will introduce such mapping at "socket" level, so "RoutedClientSideConnection" + "ServerSideConnectionPeer".
Then the socket is closed the cache will be automatically cleared.
In the current implementation (0.7.0) each client opens only one socket to each server: maybe this will change in the future.

As the JDBC driver has no control about reconnection, this mechanism must be transparent to it, we can add some "flag" in order to inform RoutedClientSideConnection that the statement is likely to be reused (like when the command is coming from a JDBC PreparedStatement)

*Wire protocol details*

Introduce a new RPC PREPARE_SQL(string), with a result PREPARE_SQL_RESULT(long statementId)
On the EXECUTE_STATEMENT, EXECUTE_STATEMENTS and OPEN_SCANNER RPC introduce a new parameter "long statementId" (0 means "no prepared statement", >0 means "use prepared statement and "query" will be the empty string)

**Comment by schrepfler** [comment]
Nice, there are analogies with GraphQL/Relay persisted queries, maybe a nice experiment would be to build GraphQL queries on top of herddb.

**Comment by eolivelli** [comment]
@schrepfler it sounds interesting!

This issue in particular is only about a wire protocol enhancement, HerdDB already implements caching for execution plans and several improvements for prepared-statement like workflows.

Let us know about your experiments, maybe using the users or dev mailing lists will be the best way to discuss (you can find links in herddb.org website), or simply just create issues on github
