### ISSUE TITLE
Add Travis-CI automatic build of Pull requests

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#303]
Shall we enable Travis-CI for builds of PRs ?
I have already tried it on my fork (https://github.com/eolivelli/herddb) and it is working great !

cc @aluccaroni @diegosalvi

**Comment by aluccaroni** [comment]
Seems a good idea

**Comment by eolivelli** [comment]
@aluccaroni  I have no permission on this repo, the repository is already ready (travis config file is already on master).
Do you have the permissions to add the project to Travis ?

**Comment by eolivelli** [comment]
see
https://github.com/diennea/herddb/blob/master/.travis.yml
