### ISSUE TITLE
Checkpoint: reduce PK lookup

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#333]
During checkpoint dirty page cleanup there is a double PK lookup in primary index:
- first one to discover if the row is "good":
`if (currentPageId == null || !weighted.pageId.equals(currentPageId)) {`
- the second one in page creation (`createImmutablePage`) to overwrite the page in the primary index:
`keyToPage.put(key, pageId);`

We could rewrite the procedure to avoid double PK lookup adding a method putIf(key,pageID,expectedPageID). It should permit to check if the record must be moved away and insert the new value at the same time

**Comment by eolivelli** [comment]
@diegosalvi good catch!

This will speed up checkpoint, especially in the case that we need to swap in/swap out PK pages due to low memory.

I guess it is not a trivial patch, but worth trying
