### ISSUE TITLE
Add metrics for checkpoint

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#339]
We should have a metric in order to measure checkpoint time.
We need two value (OpsStatsLoggers):
- per tablespace
- per table

This way will will be able to count checkpoints and track the execution time.

**Comment by eolivelli** [comment]
@amitvc this could be a good starting point.

Hints for the implementations:
Pass a the StatsLogger  [mainStatsLogger](https://github.com/diennea/herddb/blob/4e42956c4aaf17c7f61698bd425a614a7f28ed4a/herddb-core/src/main/java/herddb/core/DBManager.java#L185) to the TablespaceManager at creation time.

the StatsLogger will be a child of the mainStatsLogger, with name=the logical name of the tablespace.

Wrap the [checkpoint](https://github.com/diennea/herddb/blob/4e42956c4aaf17c7f61698bd425a614a7f28ed4a/herddb-core/src/main/java/herddb/core/TableSpaceManager.java#L1529) method with a try/finally and track a "successfullEvent" in the finally, passing the number of milliseconds as argument


you are able to see the "metrics" at http://server:httpport/metrics

the server writes the metrics endpoint in the main log at boot
```
bin/service server start
grep "metrics" service.server.log
```

**Comment by amitvc** [comment]
Couple of questions - 
1. The new OpStatsLogger will be part of the main PrometheusMetricsProvider->opstats map?
2. Each time new TableSpace is created there will be a new DataSketchesOpStatsLogger created for it? 
3. The reason you want me to pass the PrometheusMetricsProvider instance to TableSpaceManager is because that class is responsible for an individual TableSpace ? 
4. TableSpace is like a Database in the herddb world? 
5. What is purpose of TableSpaceManagerStats?

**Comment by eolivelli** [comment]
@amitvc sorry for late reply

> The new OpStatsLogger will be part of the main PrometheusMetricsProvider->opstats map?

Yes but this is handled by BookKeeper Stats implementations, no matter for us

> Each time new TableSpace is created there will be a new DataSketchesOpStatsLogger created for it?

Yes, you will have at most 1.000 tablespaces in a running serve, it is not a problem, do you see an issue with this approach ?

> The reason you want me to pass the PrometheusMetricsProvider instance to TableSpaceManager is because that class is responsible for an individual TableSpace ?

No, the TableSpaceManager will have a StatsLogger not a full MetricsProvider

>     TableSpace is like a Database in the herddb world?

Yes, in HDBC terms is like a "schema", a "database" in MySQL/SQLServer/PostGree terms

>     What is purpose of TableSpaceManagerStats?

That is for JMX API, actually we are dismissing it in favour of BookKeeper Stats API.
We are going to switch to Prometheus but BookKeeper Stats API. allows the user to use other implementations like the Dropwizard library which provides JMX export of data (see [here](https://github.com/apache/bookkeeper/tree/master/bookkeeper-stats-providers/codahale-metrics-provider)).


You can see HerdDB metrics at http://your-machine-name:9845/metrics after starting the server.

**Comment by amitvc** [comment]
@eolivelli Thanks for the response. I don't see a problem with adding new DataSketchesOpStatsLogger with new TableSpace. I will work on it tonight.

**Comment by amitvc** [comment]
From ServerMain.java - Why is a statsLogger being created without a name?        
StatsLogger statsLogger = statsProvider.getStatsLogger("");

**Comment by amitvc** [comment]
@eolivelli pull requests - https://github.com/diennea/herddb/pull/342

**Comment by eolivelli** [comment]
> From ServerMain.java - Why is a statsLogger being created without a name?
> StatsLogger statsLogger = statsProvider.getStatsLogger("");

It is how BookKeeper Stats Logger works, it is the 'root' logger
