### ISSUE TITLE
Support non null constraints - JDBC support

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#347]
With #345 we have introduced the server side handler for NOT-NULL column data types.

Two tasks on the JDBC driver:
1) We have to create end-to-end JDBC tests with NOT-NULL columns, and assert that the client will receive an SQLException.
2) We have to full support the NULLABLE metadata in DatabaseMetaData#getColumns

for 1)
Let's add a simple unit tests which creates a TABLE with all NON NULL datatypes and create tests to trigger the error (one assertionl per column, not only a single INSERT/UPDATE)

for 2)
https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)

see on "herddb-core":
https://github.com/diennea/herddb/blob/master/herddb-core/src/main/java/herddb/core/system/SyscolumnsTableManager.java#L71

here we have to report as NULLABLE = 0:
- all columns in the PK (already implemented)
- all columns with a NON_NULL datatype    (a new ColumnTypes.isNonnullableDataType(int) function is to be created)

see on "herddb-jdbc" module
https://github.com/diennea/herddb/blob/master/herddb-jdbc/src/main/java/herddb/jdbc/HerdDBDatabaseMetadata.java#L826
https://github.com/diennea/herddb/blob/master/herddb-jdbc/src/main/java/herddb/jdbc/HerdDBDatabaseMetadata.java#L869
https://github.com/diennea/herddb/blob/master/herddb-jdbc/src/main/java/herddb/jdbc/HerdDBDatabaseMetadata.java#L950

we have to create tests in JDBC module around getColumns

**Comment by eolivelli** [comment]
cc @amitvc  this is the followup issue of #345

**Comment by amitvc** [comment]
I will start work on this once I close #345

**Comment by amitvc** [comment]
@eolivelli for the UT in jdbc module is it new class or I need to add more tests to existing classes of unit tests?

**Comment by eolivelli** [comment]
@amitvc  this is the task I was referring in the ML

**Comment by amitvc** [comment]
Started work on this.

**Comment by amitvc** [comment]
@eolivelli There are several methods in BasicHerdDBDatasource.java class that are never being used in the code base See example below -
 setWaitForTableSpaceTimeout,getWaitForTableSpace,isDiscoverTableSpaceFromQuery,setDiscoverTableSpaceFromQuery. There are few more.

**Comment by eolivelli** [comment]
We should have test cases.
Actually some of them are used by downstream applications.
We can create a task for better code coverage

**Comment by amitvc** [comment]
@eolivelli I added a UT in jdbc/SystemTablesTest.java to demonstrate that we throw the exception when not null constraint is applied for non supported types. Appropriate exception is thrown here - https://github.com/diennea/herddb/blob/master/herddb-core/src/main/java/herddb/server/ServerSideConnectionPeer.java#L705

Currently we dont catch this exception and hence it is not being propagated back to the client over the network. I am guessing we need to handle these things and also interpret them on the client side. Do we have existing protocol or message types defined that we use to communicate these things ?


Exception -- 
herddb.model.StatementExecutionException: Not null constraints not supported for column type 6
	at herddb.model.ColumnTypes.getNonNullTypeForPrimitiveType(ColumnTypes.java:105)
	at herddb.sql.DDLSQLPlanner.buildCreateTableStatement(DDLSQLPlanner.java:369)
	at herddb.sql.DDLSQLPlanner.plan(DDLSQLPlanner.java:293)
	at herddb.sql.DDLSQLPlanner.translate(DDLSQLPlanner.java:270)
	at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:242)
	at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:705)

**Comment by eolivelli** [comment]
this is done, thanks @amitvc
