### ISSUE TITLE
Overlapping dependencies in JDBC uber jar

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#352]
During build on 0.9 I see these bad logs.
We have both netty-all and netty-xxx on the classpath, at least for the JDBC driver

[WARNING] netty-all-4.1.30.Final.jar, netty-transport-4.1.31.Final.jar define 350 overlapping classes: 
[WARNING]   - io.netty.channel.socket.nio.NioSocketChannel$3
[WARNING]   - io.netty.channel.AbstractCoalescingBufferQueue
[WARNING]   - io.netty.channel.AbstractChannel$AbstractUnsafe$8
[WARNING]   - io.netty.channel.SimpleUserEventChannelHandler
[WARNING]   - io.netty.channel.DefaultChannelPipeline$2
[WARNING]   - io.netty.channel.oio.AbstractOioChannel
[WARNING]   - io.netty.bootstrap.Bootstrap$1
[WARNING]   - io.netty.channel.group.ChannelMatchers$ClassMatcher
[WARNING]   - io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe
[WARNING]   - io.netty.channel.EventLoopGroup
[WARNING]   - 340 more...

**Comment by diegosalvi** [comment]
I think that we should avoid netty-all package and let maven sort netty dependency version...
... or we could add a swarm of exclusion everywere and use netty-all.

**Comment by eolivelli** [comment]
+1 better to import only the needed packages

**Comment by eolivelli** [comment]
@amitvc  would you like to pick up this issue ?
