### ISSUE TITLE
Add a test about PrimaryIndexPrefixScan

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#358]
Coveall reports that we have no test in BLink for a PrimaryIndexPrefixScan we should add one.
Better would be to add a test that cover every PK index type

**Comment by amitvc** [comment]
@diegosalvi I can start work on this. Which tests are you referring here? BlinkTest, BLinkConstantSizeTest ?

**Comment by diegosalvi** [comment]
We never enter in the branch  `if (operation instanceof PrimaryIndexPrefixScan) ` in BLinkKeyToPageIndex.scanner:167

I'd expect something like PrimaryIndexScanRangeTest but for prefix scans. (Btw PrimaryIndexScanRangeTest just test memory pk [ConcurrentMapKeyToPageIndex] and not BLink).

BLinkTest and BLinkConstantSizeTest test BLink tree structure but we need to test his usage from a PK perspective (and test BLinkKeyToPageIndex)

**Comment by eolivelli** [comment]
@amitvc do you need more info?

**Comment by amitvc** [comment]
@diegosalvi thanks for the information. I got busy with something else last week. Plan is to start work on this tonight.

**Comment by amitvc** [comment]
@diegosalvi We need to add a new UT PrimaryIndexPrefixScanTest ?
In the PrimaryIndexScanRangeTest class I see bunch of range scan queries in the format - 
 "SELECT n1,n2 FROM tblspace1.t1 WHERE n1>=2 and n2<=6 order by n1". 
Do we have examples of prefix scan queries?  What is the difference? I see in SimpleIndexAccessTest that we have some tests around PrimaryIndexPrefixScan but what determines that the indexOperation is PrimaryIndexPrefixScan?

**Comment by amitvc** [comment]
@diegosalvi I think I found the answer to how the PrimaryIndexPrefixScan IndexOperation is used. I went through some code that creates CompiledSQLExpression inside CalcitePlanner.

**Comment by eolivelli** [comment]
Yes @amitvc add a new specific UT.
Just start the server, create a table with composite pk (two columns) and issue queries that are filtering the first column in the pk.

**Comment by amitvc** [comment]
@eolivelli thanks. I have got the unit tests going. Actually got to learn more about FileDataStorageManager and MemoryDataStorageManager. The BLinkKeyToPageIndex is only available when we use FileDataStorageManager? Why is that the case ?

**Comment by eolivelli** [comment]
Blink is used in production and needs the disk, in order to store more data then available heap.
The memory implementation is only for tests of HerdDB and especially for downstream applications.

**Comment by eolivelli** [comment]
If you can't swap to disk it is not useful to have blink

**Comment by amitvc** [comment]
@diegosalvi @eolivelli PR for this https://github.com/diennea/herddb/pull/382 and thank you answering my questions.

**Comment by diegosalvi** [comment]
Closed by #382
