### ISSUE TITLE
Return appropriate COLUMN_NAME for column types with not null constraints.

### ISSUE THREAD

**Issue by amitvc** [diennea/herddb#372]
Is this a question, a feature request or a bug report?
Its an enhancement.

**QUESTION**

Have you checked our documentation in the GitHub Wiki?
If you could not find an answer there, please consider asking your question on our mailing list at herddb-users@lists.herddb.org.

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

3. Provide any additional detail on your proposed use case for this feature.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
- [ ] [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 discription here, 
- [ ] [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 discription here,
- ...

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

- What did you expect to see?

- What did you see instead?

**Comment by aluccaroni** [comment]
@amitvc can we close this issue?

**Comment by amitvc** [comment]
Yes
