### ISSUE TITLE
Missing license header - fix and plan for the future

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#394]
**TASK**

1. Please describe the issue you observed:

We missed some Apache header in some recent (and not so recent) pull. For example I can see it missing still from PrimaryIndexPrefixScanTest.java and ColumnTypesTest.java

We should also consider some way to automate this check and stop the merging of file without the license header.

@amitvc can you check the 2 pages above and fill a pull to fix them?
@eolivelli @diegosalvi @amitvc what do you think about the automation of the check? Is it feasible?

**Comment by eolivelli** [comment]
We can use checkstyle or apache rat

**Comment by amitvc** [comment]
I can add it to new file template in my IDE. @aluccaroni I will fix the 2 mentioned files. I wonder if we can use a predefined git hook that can help with this and won't allow commits to go through unless there are license headers. 
https://medium.com/cognitio/verify-license-header-before-commit-2eb0c1841121

**Comment by eolivelli** [comment]
I will setup the automatic check soon

**Comment by aluccaroni** [comment]
Fixed in https://github.com/diennea/herddb/pull/533
