### ISSUE TITLE
Implement SQLIntegrityConstraintViolationException for Primary Key Violations

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#396]
We should at least report to the client this specific exception in case of PK violation
https://docs.oracle.com/javase/7/docs/api/java/sql/SQLIntegrityConstraintViolationException.html

This will help the client understand programmatically the difference from a generic SQL error from that specific case.

We could then follow up with supporting SQLSyntaxErrorException.

In order to have this information we have to carry the error type on the wire, trying to be compatible with 0.9.0 clients (at least)

**Comment by amitvc** [comment]
@eolivelli Currently the tableManager throws **DuplicatePrimaryKeyException** exception for duplicate key. Are you saying we should instead throw **SQLIntegrityConstraintViolationException** exception across the wire? Do we support foreign key violation in herddb yet?

**Comment by eolivelli** [comment]
> Do we support foreign key violation in herddb yet?
Not yet.

For the implementation: you have to add a new FLAG_DUPLICATEPRIMARY_KEY_ERROR in PduCodec#ErrorResponse.

You have to handle it for EXECUTE_STATEMENT and EXECUTE_STATEMENTS.

In the tests please assert that this error does not corrupt the transaction, for instance:
``` 
BEGIN TRANSACTION   (this is autocommit = false, in JDBC java.sql.Connection)
INSERT INTO TABLE(pk,n1) values(1,1) --> SUCCESS
INSERT INTO TABLE(pk,n1) values(1,1) --> ERROR!
INSERT INTO TABLE(pk,n1) values(2,1) --> SUCCESS
COMMIT --> SUCCESS
```

The typical usage for this feature is to try to INSERT a value and react with an UPDATE in case of SQLIntegrityConstraintViolationException
