### ISSUE TITLE
upgrade to calcite 1.21

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#399]
Calcite 1.20 has brand new support for joins, the switch won't be trivial

https://github.com/apache/calcite/blob/calcite-1.20.0/site/_docs/history.md

**Comment by eolivelli** [comment]
@amitvc this would be a great issue for you.
It won't be easy but you will understand deeply how Calcite works

**Comment by amitvc** [comment]
@eolivelli I am really excited to work on this. Thanks for thinking about me for this issue. I will start looking into this tonight.

**Comment by eolivelli** [comment]
Calcite 1.20 has mot been released yet.
You have to build it locally on your box.
Just clone it from github and run 'mvn clean install -DslipTests

**Comment by amitvc** [comment]
Will do. I see we support left/right inner/outer joins. Are there features in calcite 1.20 that we are currently not supporting?

**Comment by amitvc** [comment]
@eolivelli Here is what I am going to do tomorrow. I have calcite 1.20 built locally. I will change the current dependency in pom to point to my locally built calcite. Then start running tests etc. I believe there might be api changes and things might break. I will work through those. Is there anything specific I should be aware with calcite 1.20 ?

**Comment by eolivelli** [comment]
I think that ' joins' will be our pain...

**Comment by amitvc** [comment]
I have made changes to upgrade calcite 1.20. Some UT are broken and I am fixing them right now.

**Comment by eolivelli** [comment]
@amitcv great news!

You can push a draft PR for early review if you want.
Calcite 1.20 has been released

**Comment by amitvc** [comment]
@eolivelli 
https://github.com/diennea/herddb/pull/404
Broken UT - https://github.com/diennea/herddb/blob/master/herddb-core/src/test/java/herddb/sql/SimplerPlannerTest.java#L244
The expected value is Long but returned value is Integer. Trying to figure out the problem.

**Comment by eolivelli** [comment]
I think you can change the test.
In the test we are working with an *int* column.
It is worth to try to add a test with a *long* column and see if the result is then a *long*.

On the jdbc driver we are always coercing the value to the type requested by the app (getInt, getLong) so there is no BC issue
