### ISSUE TITLE
Memory Bounded Collections Framework

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#401]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I would like to use HerdDB internal features in order to create (Tree-like)Maps with hard constraints on memory usage.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). 
nice-to-have

3. Provide any additional detail on your proposed use case for this feature.

We are using www.mapdb.org but we have problems with:
- Filesystem usage (JVM crashes, bad mechanical sympathy with underlying disks)
- Cannot configure a real bound on memory

**Comment by eolivelli** [comment]
@amitvc FYI. I will work on this issue soon, maybe we can defer 0.10.0 or it will be for 0.10.1

**Comment by amitvc** [comment]
@eolivelli I will review your changes over the weekend.

**Comment by aluccaroni** [comment]
@eolivelli  @amitvc  can we close this issue?

**Comment by eolivelli** [comment]
This is in production
