### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [diennea/herddb#406]
Hi
The following lines have cryptographic API misuses. <br> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 64: API name => MessageDigest:First parameter (with value "sha-256") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 44: API name => MessageDigest:<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 86: API name => MessageDigest:<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 65: API name => MessageDigest:<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 85: API name => MessageDigest:First parameter (with value "md5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 43: API name => MessageDigest:First parameter (with value "sha-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 44: API name => MessageDigest:<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 65: API name => MessageDigest:<BR> File name => herddb-net/src/main/java/herddb/network/HashUtils.java: Line number => 86: API name => MessageDigest:<BR>

**Comment by aluccaroni** [comment]
Please, check your script for case-sensitivity (or double check your reports in the code beforse sending them). 

sha-256 vs SHA-256 is not a problem
md5 is used in SASL DIGEST-MD5 auth
sha1 is not used

Created https://github.com/diennea/herddb/issues/424 for future reference
