### ISSUE TITLE
HerdDB Collections  - do not perform Files#createDirectories at every page write

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#418]
Under heavy load (frequent index page writes) Files#createDirectories adds too much overhead on the FS.

We can simply ensure that the directory for an index or for a page exists at boot and fail in case is is removed during server execution.

**Comment by diegosalvi** [comment]
It make sense. Removing a index directory during normal operation would cause index failure ... even if we recreate the directory structure. It doesn't add any useful
