### ISSUE TITLE
Add checkstyle checks

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#445]
We have to setup checkstyle with the same config of Blobit project.
https://github.com/diennea/blobit

**Comment by eolivelli** [comment]
Hello @TisonKun !

now that you are a master of checkstyle, do you have cycles to use your tools on this project?

Here the community is smaller then in Zookeeper, there won't be much nitpicking :)

It wil be a good way to get in touch with the project

**Comment by TisonKun** [comment]
Hi @eolivelli !

Thanks for your introduce. I would like to give it a try in this week.

To be clear we would use a rules set almost follow that in diennea/blobit ?

**Comment by eolivelli** [comment]
Great!

Pleease use the same file please. That in turn very like to the Bookkeeper file, without javadoc rules and some more suppression.

For the line length rule feel free to cut the lines in whatever way is better for your automatic tools.

Thank you so much
