### ISSUE TITLE
PRIMARY KEY not parsed correctly when executed via CLI - Was "Discrepancy between CREATE TABLE and SHOW CREATE TABLE commands when using auto_increment"

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#468]
**BUG REPORT**

1. Please describe the issue you observed:

I seem to be unable to create a table with an autoincrement column.
If I run this query:
`create table mytablespace.test2 (ID long auto_increment, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255),PRIMARY KEY (id) )`

And then run a "SHOW CREATE TABLE test2", the output is:
`CREATE TABLE mytablespace.test2(id long,lastname string,firstname string,address string,city string,PRIMARY KEY(id)) `

The column "id" seems to have no auto_increment flag, and I can confirm that by running:
`insert into test2 values (null,'Luccaroni','Alessandro','via Glicini 8','Faenza')`

```
Executing query:insert into test2 values (null,'Luccaroni','Alessandro','via Glicini 8','Faenza')
ERROR:java.sql.SQLException: herddb.model.StatementExecutionException: From line 1, column 19 to line 1, column 81: Column 'id' has no default value and does not allow NULLs
```

If, instead, we run this create table (without declaring the PK):
`create table mytablespace.testpk (ID long , LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255) )`

And then run a "SHOW CREATE TABLE testpk", the output is:
`CREATE TABLE mytablespace.testpk(id long,lastname string,firstname string,address string,city string,_pk long auto_increment,PRIMARY KEY(_pk))`

The pk column _pk is created with the auto_increment flag, and it works:
`insert into testpk values (1,'Luccaroni','Alessandro','via Glicini 8','Faenza',null)
`
```
select * from testpk
| id | lastname  | firstname  | address       | city   | _pk |
| -- | --------  | ---------  | -------       | ----   | --- |
| 1  | Luccaroni | Alessandro | via Glicini 8 | Faenza | 1   |
```

**Comment by aluccaroni** [comment]
It seems to be a problem with the query parsing, if I run the following query it works:
`create table mytablespace.test5 (ID long AUTO_INCREMENT PRIMARY KEY, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255))`

Please note that the first query that I've used (and don't work) is the one outputted by SHOW CREATE TABLE:
`CREATE TABLE mytablespace.test5(id long auto_increment,lastname string,firstname string,address string,city string,PRIMARY KEY(id))`

**Comment by aluccaroni** [comment]
To add info to this problem: it seems that PRIMARY KEY as a last entry works IF the pk is on multiple column

**Comment by eolivelli** [comment]
@amitvc do you want to pick this up ?
IIRC it is about a feature from you

**Comment by amitvc** [comment]
@eolivelli I will pick this one. Thank you.

**Comment by amitvc** [comment]
@eolivelli  I think I have found the issue. I will push the change shortly.

**Comment by amitvc** [comment]
@eolivelli [PR](https://github.com/diennea/herddb/pull/495)

**Comment by aluccaroni** [comment]
Close with https://github.com/diennea/herddb/pull/495
