### ISSUE TITLE
Create official docker images for HerdDB

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#470]
We should provide an official image for running HerdDB standalone and a cluster.

In standalone mode data is to be persisted on one or more volumes (data, journal, metadata)
In cluster mode we should coordinate with an existing ZooKeeper cluster, we can use the Embedded Bookie.
It is worth to think about not using the EmbeddedBookie as some @apache/pulsar users already have a BookKeeper cluster (and a ZooKeeper one)

**Comment by eolivelli** [comment]
@Cobra1978 this is your field :-)

**Comment by Cobra1978** [comment]
Ready to work on it ;)

**Comment by aluccaroni** [comment]
@Cobra1978 take a look to https://github.com/diennea/herddb/wiki/Getting-started
For the cluster version we have 2 possibilities: use embedded Bookie or separate BookKeeper (for the zookeeeper we need to use a separate cluster...maybe we could add some info about existing ZK recipes)

**Comment by Cobra1978** [comment]
I think that the best solution is to create a single image, which could optionally use external bookkeper, so for the cluster version we only need to provide a proper docker compose file, with some predefined configuration values.

Obviously we can discuss about this.

**Comment by aluccaroni** [comment]
We have these use cases:

1. single machine
2. Cluster + Embedded BK + External ZK
3. Cluster + External BK + External ZK

Cluster + Embededd ZK is not doable, since it will have a single point of failure (Embedded ZK in HerdDB support only single server installation)

**Comment by Cobra1978** [comment]
Ok.

**Comment by Cobra1978** [comment]
I will put all docker-related stuffs in herddb-docker, it hink tha the best way is to download ther release package in the docker file, and use as base image 11-jre-slim as official zookeeper does, i't ok?

**Comment by aparneshgaurav** [comment]
Kindly add me as an assignee .

**Comment by eolivelli** [comment]
@aparneshgaurav  done
thanks

**Comment by aparneshgaurav** [comment]
> @aparneshgaurav done
> thanks

Thanks .

**Comment by eolivelli** [comment]
@aparneshgaurav do you have troubles ?
maybe you can post a draft pull request, this way we can see your work and help

**Comment by aparneshgaurav** [comment]
@eolivelli , ok , will do that . Had been caught up with some company work , will start this weekend on this .

**Comment by eolivelli** [comment]
@aparneshgaurav it looks like @rmannibucau sent a good PR in order to have a first working docker image.
We need it for the ApacheCon talk.

The work won't be finished, it is only the first step, because we will have to publish the image and created detailed instructions
