### ISSUE TITLE
Create scripting for HerdDB Cli on Windows

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#493]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

New windows developers and ops need a CLI script for Windows (bat file?)

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

must-have

**Comment by aluccaroni** [comment]
Resolved with https://github.com/diennea/herddb/pull/499
