### ISSUE TITLE
It's Possible to NOT insert values in a 'NOT NULL' field

### ISSUE THREAD

**Issue by GiacomoCorezzi** [diennea/herddb#508]
**BUG REPORT**

1. Please describe the issue you observed:

- I was able to omit the insertion of a data within a NOT NULL field

- What did you expect to see?
I expected not to be able to omit a NOT NULL field

**Comment by eolivelli** [comment]
@GiacomoCorezzi  how can you reproduce the issue ?
please attach the sequence of the commands (CREATE TABLE, INSERT...)
It would be also useful to see the results of SHOW CREATE TABLE xxx

**Comment by GiacomoCorezzi** [comment]
//I created this table:

CREATE TABLE Customers (
 CustomerID int NOT NULL,
 FirstName varchar(255) NOT NULL,
 LastName varchar(255),
 Age int,
PRIMARY KEY (CustomerID) 
)

//Then I ran

INSERT INTO Customers (CustomerID, LastName, Age)
VALUES (2, 'Zammarchi', 20)

//It has returned

| customerid | firstname | lastname  | age |
| ---------- | ---------     | --------       | --- |
| 1              | Giacomo    | Corezzi        | 20  |
| 2              | <NULL>    | Zammarchi | 20  |

**Comment by eolivelli** [comment]
@amitvc what do you this about this bug ? it seems that "NOT NULL" is not working, but we have test cases

**Comment by amitvc** [comment]
@eolivelli I thought we had unit tests for these and they all passed. 
I am going to look into this tonight. I will update the ticket.

**Comment by amitvc** [comment]
I am able to reproduce this on my local environment. Although the unit tests added for this specific use case still are successful. Looking into it more.

**Comment by amitvc** [comment]
@eolivelli Found the issue. Pushing fix after running regression

**Comment by amitvc** [comment]
@eolivelli  https://github.com/diennea/herddb/pull/510

**Comment by aluccaroni** [comment]
Fixed in https://github.com/diennea/herddb/pull/510
