### ISSUE TITLE
Leadership election: cannot download data of tableSpace buckets from myself

### ISSUE THREAD

**Issue by hamadodene** [diennea/herddb#539]
While using the cluster installation, I had problems with the leadership election.
A cluster node remained isolated  caused by network down (we will call it n1).
The  node m1 was the leader of the tablespace buckets, and when it went "down" the leadership moved to another node.
However, this node did not have enough data to start as a leader (we will call it n2).
We will call the third node n3.
Restarting node n2, n3 the leadership changed and passed on node n3 and everything started to work again.
This means that there is a problem in choosing the leader.
I expect that a node that does not have enough data will not be named. Maybe it's probably not important that it becomes the node with the most data, but that in a loop you try to download the data from another node and not from itself.

```
20-01-21-18-11-54       herddb.core.DBManager Jan 21, 2020 6:11:54 PM herddb.core.DBManager manageTableSpaces
SEVERE: cannot handle tablespace buckets
herddb.storage.DataStorageManagerException: cannot download data of tableSpace buckets from myself
        at herddb.core.TableSpaceManager.downloadTableSpaceData(TableSpaceManager.java:589)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:302)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:231)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:537)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1120)
        at herddb.core.DBManager.executeActivator(DBManager.java:1066)
        at herddb.core.DBManager.access$500(DBManager.java:113)
        at herddb.core.DBManager$Activator.run(DBManager.java:1009)
        at java.base/java.lang.Thread.run(Thread.java:830)
 
```

**Comment by aluccaroni** [comment]
If we know which node has the most data it's a good idea that that node will become master, but this maybe add un-needed complexity.

I prefer a simpler approach where a node at random become master and this node will guarantee, checking each replica, to become up-to-date before actually start up the tablespace...usually all the replica are very close (and, anyway, every replica needs to become consistent eventually) so this shouldn't be more expensive in the end.

**Comment by eolivelli** [comment]
We are adding a new replica automatically depending on "expectedreplicacount", but this happens only in case of an explicit lack of nodes in the "replica" field.
We are not detecting unavailable nodes and remove them from the "replica" set.

@hamadodene please check your logs for 
`Tablespace {0} is underreplicated expectedReplicaCount={1}, replicas={2}, nodes={3}`

**Comment by hamadodene** [comment]
@eolivelli I didn't find "underreplicated expectedReplicaCount"  in my logs
