### ISSUE TITLE
 Corrupted transaction log during follower recovery: key is already present in table 

### ISSUE THREAD

**Issue by hamadodene** [diennea/herddb#540]
During Herd's normal activity, i had problems while recovering tablespaces.
When node x tries to download data from node y, a duplicate key arrives at node x.
This means that the y node  (we will call it "myhostname/myip") during the full checkpoint does not actually remove all duplicates.

Stacktrace below:
```
20-01-22-15-56-12       herddb.network.netty.NettyChannel Jan 22, 2020 3:56:12 PM herddb.network.netty.NettyChannel lambda$handlePduRequest$0
SEVERE: NettyChannel{name=myhostname:7000, id=13, socket=[id: 0xe6347342, L:/10.162.1.11:38666 - R:myhostname/myip:7000] pending 0 msgs}: error java.lang.IllegalStateException: corrupted transaction log: key 0800000000005c4bd70400000001124c4f43414c2042494e442041444452455353 is already present in table q2_additional_info
java.lang.IllegalStateException: corrupted transaction log: key 0800000000005c4bd70400000001124c4f43414c2042494e442041444452455353 is already present in table q2_additional_info
        at herddb.core.TableManager.applyInsert(TableManager.java:1957)
        at herddb.core.TableManager.writeFromDump(TableManager.java:1872)
        at herddb.core.ReplicaFullTableDataDumpReceiver.receiveTableDataChunk(ReplicaFullTableDataDumpReceiver.java:105)
        at herddb.client.RoutedClientSideConnection.requestReceived(RoutedClientSideConnection.java:203)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)

```

**Comment by eolivelli** [comment]
@hamadodene using the database you sampled fro the environment I am able to reproduce exactly the error on the same key locally on a test case.
Unfortunately the database is huge and I cannot push it to github :-)

**Comment by hamadodene** [comment]
@eolivelli  perfect!

**Comment by eolivelli** [comment]
In your case the 'dirt' sum of page 9.433 is 0, so the page is not marked as "dirty" and we are not compacting it

**Comment by eolivelli** [comment]
if I change
`if (dirt > 0 && dirt >= dirtyPageThreshold) {`
to
`if (dirtyPageThreshold == 1 || dirt > 0 && dirt >= dirtyPageThreshold) {`

I get (expected??)
`Data inconsistency! Found a clean page with dirty records based on PK data. It could be a key to page inconsistency (broken PK) or a page metadata inconsistency (failed to track dirty record on page metadata). Page: 9422:0, Record Record{key=0800000000005c2c7804000000011052454d4f544520534d545020494e464f, value=030bb8033232302065732d636c69656e742e7376696c7570706f2e646e612045534d54502044756d6d79534d54500a45484c4f2065732d646576312e7376696c7570706f2e646e610a3235302d65732d636c69656e742e7376696c7570706f2e646e610a3235302d384249544d494d450a3235302d5354415254544c530a323530204f6b0a5354415254544c530a32323020526561647920746f20737461727420544c530a45484c4f2065732d646576312e7376696c7570706f2e646e610a3235302d65732d636c69656e742e7376696c7570706f2e646e610a3235302d384249544d494d450a3235302d5354415254544c530a323530204f6b0a4d41494c2046524f4d3a3c626261636b67656d696e692e6d6e6964326d2e3132392e3530303036372e33372e302e343132352e63343132353536303337342e5f40716173716c2e7376696c7570706f2e646e613e0a323530204f6b0a5243505420544f3a3c656d61696c343939303638406e6f6e6573697374652e6469656e6e65612e636f6d3e0a323530204f6b0a444154410a33353420456e6420646174612077697468203c43523e3c4c463e2e3c43523e3c4c463e0a2e0a323530204f4b0a}
	`

**Comment by diegosalvi** [comment]
I'm really afraid of a wrong dirty count... :/
