### ISSUE TITLE
Implement basic DATETIME functions

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#589]
Implement basic datetime functions, like YEAR, MONTH, DATE....
They are supposed to work only on Timestamp data type.

We should deal with Timezones....any suggestion is welcome.
ideas:
- use a single static timezone, configured by a configuration parameter
- handshake a timezone per connection, with default to local server timezone for old clients

we must check now Calcite deals with such functions

**Comment by amitvc** [comment]
I will start to see how latest calcite deals with the date/time functions.
