### ISSUE TITLE
how many company use this db? how many nodes you  use? scenes to be used？

### ISSUE THREAD

**Issue by huashen** [diennea/herddb#598]
Is this a question, a feature request or a bug report?

**QUESTION**

Have you checked our documentation in the GitHub Wiki?
If you could not find an answer there, please consider asking your question on our mailing list at herddb-users@lists.herddb.org.

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

3. Provide any additional detail on your proposed use case for this feature.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
- [ ] [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 discription here, 
- [ ] [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 discription here,
- ...

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

- What did you expect to see?

- What did you see instead?

**Comment by eolivelli** [comment]
Hello @huashen 
Currently HerdDB is used in nonOS products of our company:
- https://www.magnews.com
- https://emailsuccess.com

It is also used in OS projects like:
- Apache Pulsar Manager (https://github.com/apache/pulsar-manager)
- CarapaceProxy (https://github.com/diennea/carapaceproxy)
- BlobIt (https://github.com/diennea/blobit)

There is also an integration for MyBatisPager: https://github.com/GitHanter/mybatis-pager

It targets clusters of 1-10 machines with hundreds of tablespaces with tens of tables.

It is well suited for write intensive workloads, especially for accesses to single row (INSERT, UPSERT, DELETE, GET by PK)

If you are interested feel free to share your usecase and we could help you in understanding if it fits your needs.

**Comment by huashen** [comment]
Thank you
