### ISSUE TITLE
Implement "TIMESTAMP not null", "BLOB not null" and "FLOAT NOT NULL"

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#620]
While porting an application from SQLServer to HerdDB an user reported the need of "TIMESTAMP not null" data type

**Comment by eolivelli** [comment]
@amitvc to you have cycles to work on this ?
you already implemented NOT NULL for strings and other  datatypes

**Comment by amitvc** [comment]
I will get on it this weekend.

**Comment by amitvc** [comment]
Working on it. Will get a PR out soon.

**Comment by eolivelli** [comment]
Great.
Please check that we will be covering all supported data types.
