### ISSUE TITLE
PreparedStatement#setCharacterStream not supported

### ISSUE THREAD

**Issue by rmannibucau** [diennea/herddb#633]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Use stream API of statements

- What did you expect to see?

Nothing ;)

- What did you see instead?

    Caused by: java.sql.SQLException: Not supported yet.
	at herddb.jdbc.HerdDBPreparedStatement.setCharacterStream(HerdDBPreparedStatement.java:254)

**Comment by eolivelli** [comment]
The fix #635 is will be shipped in 0.17.0.
The fix is only on the JDBC driver, it will be compatible with previous versions of the server
