### ISSUE TITLE
Something fishy with openjpa

### ISSUE THREAD

**Issue by rmannibucau** [diennea/herddb#634]
**QUESTION**

I wanted to give a try with openjpa but I got several issues and one is that the DDL do not seem to work:

```
Caused by: org.apache.openjpa.lib.jdbc.ReportingSQLException: herddb.model.TableAlreadyExistsException: openjpa_sequence_table
	at herddb.core.TableSpaceManager.createTable(TableSpaceManager.java:1458)
	at herddb.core.TableSpaceManager.executeStatementAsyncInternal(TableSpaceManager.java:1282)
	at herddb.core.TableSpaceManager.executeStatementAsync(TableSpaceManager.java:1238)
	at herddb.core.DBManager.executeStatementAsync(DBManager.java:662)
	at herddb.core.DBManager.executePlanAsync(DBManager.java:719)
	at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:722)
	at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:139)
	at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:97)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
 {stmnt 609116570 CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID))} [code=0, state=null]
```

Here is my pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>test-herdb</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.12</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.openjpa</groupId>
      <artifactId>openjpa</artifactId>
      <version>3.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.herddb</groupId>
      <artifactId>herddb-jdbc</artifactId>
      <version>0.16.1</version>
    </dependency>
  </dependencies>
  <build>
    <plugins><plugin>
      <groupId>org.apache.openjpa</groupId>
      <artifactId>openjpa-maven-plugin</artifactId>
      <version>3.1.1</version>
      <executions>
        <execution>
          <id>enhancer</id>
          <phase>compile</phase>
          <goals>
            <goal>enhance</goal>
          </goals>
          <configuration>
            <toolProperties>
              <MetaDataFactory>jpa</MetaDataFactory>
            </toolProperties>
          </configuration>
        </execution>
      </executions>
      <configuration>
        <includes>test/entity/*.class</includes>
        <sqlAction>build</sqlAction>
        <toolProperties>
          <MappingDefaults>jpa(ForeignKeyDeleteAction=restrict,JoinForeignKeyDeleteAction=restrict)</MappingDefaults>
          <MetaDataFactory>jpa</MetaDataFactory>
        </toolProperties>
      </configuration>
    </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>11</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

My entity:

```
package test.entity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class User {
    @Id
    @GeneratedValue
    private long id;
    private String name;
    //@Lob
    private String description;
}
```

The test main:

```
package test;
import herddb.server.Server;
import herddb.server.ServerConfiguration;
import org.apache.bookkeeper.stats.NullStatsLogger;
import test.entity.User;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
public class Main {
    public static void main(String[] args) throws Exception {
        final Server server = new Server(new ServerConfiguration(), new NullStatsLogger());
        server.start();
        final EntityManagerFactory factory = Persistence.createEntityManagerFactory("hdb");
        {
            final EntityManager em = factory.createEntityManager();
            final EntityTransaction transaction = em.getTransaction();
            transaction.begin();
            em.persist(new User(0, "First", "Something"));
            transaction.commit();
            em.close();
        }
        {
            final EntityManager em = factory.createEntityManager();
            System.out.println(em.createQuery("select e from User e").getResultList());
            em.close();
        }
        factory.close();
        server.close();
    }
}
```

and the persistence descriptor:

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1"
             xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
  <persistence-unit name="hdb" transaction-type="RESOURCE_LOCAL">
    <class>test.entity.User</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
      <property name="javax.persistence.jdbc.driver" value="herddb.jdbc.Driver" />
      <property name="javax.persistence.jdbc.url" value="jdbc:herddb:server:localhost:7000" />
      <property name="javax.persistence.jdbc.user" value="sa" />
      <property name="javax.persistence.jdbc.password" value="hdb" />
      <property name="javax.persistence.schema-generation.database.action" value="drop-and-create" />
      <property name="openjpa.jdbc.DBDictionary" value="org.apache.openjpa.jdbc.sql.DBDictionary(ForUpdateClause='')"/>
    </properties>
  </persistence-unit>
</persistence>
```

**Comment by eolivelli** [comment]
I have posted a fix
https://github.com/diennea/herddb/pull/637

I have added your reproducer to the repository, in order to guarantee compatibility in the future.

Unfortunately Calcite does not like tables named "User" as it is a reserved word. We cannot fix that.

Regarding the 'FOR UPDATE' syntax I will follow up with an additional fix

**Comment by rmannibucau** [comment]
@eolivelli two small comments:

1. driver will likely never be closed, I suspect the close must be handled by the server when local (same as it closes the client when it is remote). H2 has several modes like "close with last connection.close" or  "leak" for example. Guess it is relevant here too.
2. Reserved keywords are configurable (ReservedWords=User) in the openjpa dictionary. What about doing a herddb dictionary?

**Comment by eolivelli** [comment]
For 1) I agree that such feature will be useful. But it is not straightforward to implement. OpenJPA instantiates several instances of the JDBC driver and my approach seems to fix the problem but it is not good. I will rework it.

For 2) it depends on Calcite. There are a few reserved words that you cannot add

**Comment by rmannibucau** [comment]
@eolivelli 1. well, most applications use a connection pool so I guess the impl must be pool friendly and support to release (call close) at least with "last connection close" - which enables a trivial workaround for the "let it leak" case compared to current case which seems to leak between tests. For 2 I agree it is calcite but users don't care about it when using herddb so I guess the minimum is to document it on the wiki and provide a working setup (either a copy/paste persistence.xml or a dictionary impl, I'm happy to help you to get there in openjpa code but I need your helps about what should be configured exactly).

**Comment by eolivelli** [comment]
@rmannibucau I have played more with our OpenJPA example.
It looks like OpenJPA does not keep at least connection open so stopping the server every time there are zero connection is not a good way to go (the server will be always stopping and starting).

I have reworked how the JDBC driver pools the internal Datasources with global static register in order to play better with OpenJPA.

I have checked other applications that are using HerdDB with EclipseLink like this
https://github.com/diennea/bookkeeper-visual-manager/blob/master/web/src/main/java/org/bkvm/cache/MetadataCache.java#L46

And I found that they are always passing the DataSource object to the Java Persistence API, so actually there is no problem about this stuff of keeping the database open.

Is it possible to use OpenJPA with that approach ?

**Comment by eolivelli** [comment]
@rmannibucau 
regarding the HerdDB directionary, I feel it is a good idea to provide such dictionary to OpenJPA.
If you have experience of this, do you have any pointer for any contributor that would like to contribute such Dictionary ?
Meanwhile I will check OpenJPA docs :-)

**Comment by rmannibucau** [comment]
@eolivelli yes, openjpa keeps a connection open only if you set up a connection pool - not the default if you dont bring commons-dbcp, but, it is trivial in a test to open a connection for the time you need the server, this is why i mentionned it as simple to workaround and sane default compared to alternative. That said the "leak" mode toggle is a nice to have too. Note that all JPA providers have both modes: datasource or custom DriverManager based impl so you can get the same issues with all providers. My point is more it is easy to handle it in herddb and align the default behavior to what most java users will expect due to other embedded DB (hsqldb, h2, derby).
Finally, about openjpa dictionary, I would recommend you to have a look to DBDictionary inheritance, grab the DB impl you are the most familiar with. High level, DBDictionary provides a generic, highly customizable impl, children just preconfigure some defaults + override rare cases the SQL languages can be more specific.
Don't hesitate to ping me if needed.
