### ISSUE TITLE
Memory-based page flush strategy

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#65]
To lower the number of write to disk and to ensure that the in memory storage doesn't cause memory problems to the JVM we need to base the page flush strategy on the actual memory available to the JVM.

I propose we follow a strategy similar to hbase, so:

* If table inMem store > server.memstore.table.limit (Default 300 MB)
-> flush one page to disk
* If total inMem store > server.memstore.globallimit.hi (Default  40% heap)
-> flush one page to disk starting from the biggest inMem store
-> repeat until total inMem store < server.memstore.globallimit.low (35% heap)

During periodic checkpoint we need to continue to flush ALL the pages to ensure consistency and recovery speed

variable in service.conf:
server.memstore.globallimit.hi=40%
server.memstore.globallimit.low=35%
server.memstore.table.limit=300

**Comment by eolivelli** [comment]
I'm working on it
see this https://github.com/diennea/herddb/wiki/Memory-usage-and-configuration

**Comment by eolivelli** [comment]
@aluccaroni I have pushed the first complete impl. can you check ?

**Comment by eolivelli** [comment]
Thet work is going on (see for instance https://github.com/diennea/herddb/commit/cae655cfcfe939de8a72eee8c343f3a58b12e891) but a Strategy to decide which page is to be swapped out is to be defined.

in general we are suffering on Full table scans where the table does not fit the max size, and this is true for most production trablss

**Comment by eolivelli** [comment]
the same strategy (or similar) need to be applied  to indexes too

**Comment by eolivelli** [comment]
@diegosalvi is implementing a new strategy based on CAR. this will allow use to put a global upper bound on the overall memory used

**Comment by eolivelli** [comment]
# maximum amount of memory (in bytes) used for readonly pages
#server.memstore.page.limit=

# maximum amount of memory (in bytes) used for dirty data (new/updated records)
#server.memstore.dirty.limit=

# threshold to trigger 'dirty memory' clean up
#server.memstore.dirty.hi=

# lower bound on 'dirty memory' clean up
#server.memstore.dirty.low=

# overall limit on memory usage. it defaults to maximum heap size configured on the JVM
#server.maxmemory.reference=

**Comment by diegosalvi** [comment]
In addition to ClockAdaptiveReplacementPolicy, added a RandomReplacementPolicy. Implementation can be switched with system property: "MemoryManager.pageReplacementPolicy", set to "car" or "random". Defaults to "car".

**Comment by diegosalvi** [comment]
Added a new PageReplacementPolicy: ClockProPolicy, "MemoryManager.pageReplacementPolicy" defaults to "cp"

**Comment by diegosalvi** [comment]
Added a paged implementation of BRIN indexes... To really close memory issues primary keys must handled too

**Comment by eolivelli** [comment]
created #90 for the last part
