### ISSUE TITLE
Use tablespace replication factor (expectedreplicacount) as configuration for BK write quorum size 

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#661]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Currently it is hard for users to configure correctly the replication parameters, because we have:
- BK level configuration, to be configured per-server
- replication factor (expected replica count), configured per-tablespace.

This situation also prevents to have tablespaces with different replication constraints regarding BK (the write ahead log)

It would be better to:
- use expectedreplicacount as default ensemblesize/writequorumsize/ackquorumsize
- allow to force ensemblesize/writequorumsize/ackquorumsize per-server, in order to allow a backward compatible configuration

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

**Comment by eolivelli** [comment]
@aluccaroni  @diegosalvi  @amitvc @hamadodene  what do you think ?
I would like to fix this in 0.18.0 release

**Comment by hamadodene** [comment]
It would be great to have it in my opinion

**Comment by eolivelli** [comment]
committed in 0.18.0
