### ISSUE TITLE
BookKeeper EnsemblePlacementPolicy to prefer at least one write to local node

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#69]
It would be better to use always at least the "local" (embedded) Bookie in order to:
- improve speed
- have better guarantees of recovery in case of restart of the local node

**Comment by eolivelli** [comment]
When running BookKeeper inside the same JVM of Herd (that is the default mode) it would be better to have a custom EnsamblePlacemenetPolicy derived from the DefaultEnsemblePlacementPolicy policy which tries to include the "local bookie" (LocalBookiesRegistry.isLocalBookie(addr)) in the ensemble.

**Comment by caiok** [comment]
Pushed
