### ISSUE TITLE
Add more "compiled sql expressions"

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#78]
It would be great to implement as CompiledSQLExpression all of the expressions which are actually evaluated using InterpretedSQLExpression (and then drop InterpretedSQLExpression forever)

**Comment by eolivelli** [comment]
First cases to implement:
- math operators (Addition, Subtraction, Multiplication, Division, SignedExpression)
- is null
- "special" boolean operator (COLUMNNAME OPERATOR CONSTANT)
- "generic" boolean operators (expression OPERATOR expression)
- between
- case/when
- 'in'

**Comment by caiok** [comment]
Closed by [8a3cd8a](https://github.com/diennea/herddb/commit/8a3cd8ab6c71c1f3fd7b45e35ca6d6d21c0b3220) and [9aca0c3](https://github.com/diennea/herddb/commit/9aca0c3a9d710a207e034db40da655a647bcdb82)
