### ISSUE TITLE
Reduce duration of Tablespace write lock during checkpoint

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#817]
During Tablespace checkpoint we hold a global tablespace write lock, for lock checkpoints this lock can be really annoying.

We should reduce the time spent under write lock, extracting from checkpoint procedure what is not really needed and can be done later and improve some bottlenecks.

From what i see there is much time spent in the last part of tablespace checkpoint when all tables has been checkpointed but remains 
1. dropOldLedgers (done under tablespace write lock)
2. PostCheckpointAction.runs (outside tablespace write lock)

Propositions
1. We could postpone old ledger drop after the writelock release as a "PostCheckpontAction" if for any accident old ledger aren't dropped they will dropped in the next checkpoint when it will come.
2. Some time is spent during PostCheckpointActions creations. Expecially they nearly all filesystem access to search file that need deletion. This search could be much more efficient, we handle files, they don't appear from nowere. We could keep track of existing files and do such work known state on memory thus avoiding unneeded file system access and scans.
See 
actions.addAll(dataStorageManager.writeCheckpointSequenceNumber(tableSpaceUUID, logSequenceNumber))
actions.addAll(dataStorageManager.writeTransactionsAtCheckpoint(tableSpaceUUID, logSequenceNumber, currentTransactions));
dataStorageManager.writeTables(tableSpaceUUID, logSequenceNumber, tablelist, indexlist, prepareActions);
result.addAll(dataStorageManager.indexCheckpoint(tableSpace, indexName, indexStatus, pin))
and much more. Essentially every creation of PostCheckpontAction is to create a delete action and such delete action is created scanning the actual file system

**Comment by eolivelli** [comment]
> Expecially they nearly all filesystem access to search file that need deletion

Do you have some numbers ? it should be only list  the contents of the directory (reading the content of the directory), and not accessing metadata per each file.
It shouldn't take much time (at least on Linux)

**Comment by diegosalvi** [comment]
Unfortunately I don't have timings log anymore. This was found while looking for long checkpoints duration on production servers.
We can close this and reopen with new logs
